"""add_avatar_url_to_agents

Revision ID: 687b431d57a9
Revises: b401e39f9f56
Create Date: 2026-01-22 14:32:03.025747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687b431d57a9'
down_revision: Union[str, Sequence[str], None] = 'b401e39f9f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'avatar_url')
    # ### end Alembic commands ###
