"""Add widget configuration to agent_configs

Revision ID: 586e8e4f2fc3
Revises: cf055de9ccf2
Create Date: 2026-01-21 17:26:07.891415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586e8e4f2fc3'
down_revision: Union[str, Sequence[str], None] = 'cf055de9ccf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('widget_theme', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('widget_color', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('widget_position', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('widget_greeting', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'widget_greeting')
    op.drop_column('agent_configs', 'widget_position')
    op.drop_column('agent_configs', 'widget_color')
    op.drop_column('agent_configs', 'widget_theme')
    # ### end Alembic commands ###
