"""initial migration

Revision ID: 880081a8f17a
Revises: 
Create Date: 2026-01-08 18:11:06.037318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880081a8f17a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('user_type', sa.String(), nullable=True),
        sa.Column('credits_remaining', sa.Integer(), nullable=True),
        sa.Column('last_reset_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.create_table(
        'agents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('instructions', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)

    op.create_table(
        'user_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('widget_theme', sa.String(), nullable=True),
        sa.Column('widget_color', sa.String(), nullable=True),
        sa.Column('widget_position', sa.String(), nullable=True),
        sa.Column('widget_size', sa.String(), nullable=True),
        sa.Column('email_notifications', sa.Boolean(), nullable=True),
        sa.Column('browser_notifications', sa.Boolean(), nullable=True),
        sa.Column('notification_frequency', sa.String(), nullable=True),
        sa.Column('default_language', sa.String(), nullable=True),
        sa.Column('response_style', sa.String(), nullable=True),
        sa.Column('max_response_length', sa.String(), nullable=True),
        sa.Column('auto_suggestions', sa.Boolean(), nullable=True),
        sa.Column('data_retention_days', sa.Integer(), nullable=True),
        sa.Column('analytics_enabled', sa.Boolean(), nullable=True),
        sa.Column('share_usage_data', sa.Boolean(), nullable=True),
        sa.Column('api_rate_limit_preference', sa.String(), nullable=True),
        sa.Column('debug_mode', sa.Boolean(), nullable=True),
        sa.Column('custom_preferences', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)

    op.create_table(
        'agent_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.UUID(), nullable=False),
        sa.Column('retrieval_enabled', sa.Boolean(), nullable=True),
        sa.Column('retrieval_top_k', sa.Integer(), nullable=True),
        sa.Column('embedding_model', sa.String(), nullable=True),
        sa.Column('vector_store_namespace', sa.String(), nullable=True),
        sa.Column('system_prompt_locked', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('agent_id'),
    )
    op.create_index(op.f('ix_agent_configs_id'), 'agent_configs', ['id'], unique=False)

    op.create_table(
        'knowledge_bases',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agent_id', sa.UUID(), nullable=False),
        sa.Column(
            'source_type',
            sa.Enum('upload_pdf', 'upload_txt', 'url', 'text', 'other', name='kbsourcetype'),
            nullable=False,
        ),
        sa.Column('source_uri', sa.Text(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('status', sa.Enum('pending', 'ready', 'failed', name='kbstatus'), nullable=False),
        sa.Column('tokens_estimate', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)

    op.create_table(
        'usage_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('agent_id', sa.UUID(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('credits_used', sa.Integer(), nullable=True),
        sa.Column('message_content', sa.Text(), nullable=True),
        sa.Column('response_content', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_usage_logs_id'), 'usage_logs', ['id'], unique=False)

    op.create_table(
        'kb_ingest_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('kb_id', sa.UUID(), nullable=False),
        sa.Column('state', sa.Enum('queued', 'running', 'succeeded', 'failed', name='jobstate'), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_kb_ingest_jobs_id'), 'kb_ingest_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_ingest_jobs_id'), table_name='kb_ingest_jobs')
    op.drop_table('kb_ingest_jobs')
    op.drop_index(op.f('ix_usage_logs_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_agent_configs_id'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
