"""Add performance indexes to usage_log, knowledge_base, and kb_ingest_job tables

Revision ID: b401e39f9f56
Revises: 586e8e4f2fc3
Create Date: 2026-01-21 18:17:16.443067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b401e39f9f56'
down_revision: Union[str, Sequence[str], None] = '586e8e4f2fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_configs_agent_id_key'), 'agent_configs', type_='unique')
    op.create_index(op.f('ix_agent_configs_agent_id'), 'agent_configs', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_index(op.f('ix_kb_ingest_jobs_created_at'), 'kb_ingest_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_ingest_jobs_kb_id'), 'kb_ingest_jobs', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_ingest_jobs_state'), 'kb_ingest_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_agent_id'), 'knowledge_bases', ['agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_created_at'), 'knowledge_bases', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_status'), 'knowledge_bases', ['status'], unique=False)
    # Note: Removed agent_id type change as it should already be Integer type
    op.create_index(op.f('ix_usage_logs_agent_id'), 'usage_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_timestamp'), 'usage_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_timestamp'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_agent_id'), table_name='usage_logs')
    # Note: Removed agent_id type change as it should already be Integer type
    op.drop_index(op.f('ix_knowledge_bases_status'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_created_at'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_agent_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_kb_ingest_jobs_state'), table_name='kb_ingest_jobs')
    op.drop_index(op.f('ix_kb_ingest_jobs_kb_id'), table_name='kb_ingest_jobs')
    op.drop_index(op.f('ix_kb_ingest_jobs_created_at'), table_name='kb_ingest_jobs')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agent_configs_agent_id'), table_name='agent_configs')
    op.create_unique_constraint(op.f('agent_configs_agent_id_key'), 'agent_configs', ['agent_id'])
    # ### end Alembic commands ###
