"""add s3 storage and user storage usage

Revision ID: cf055de9ccf2
Revises: 653571ac65b6
Create Date: 2026-01-10 12:25:15.010772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf055de9ccf2'
down_revision: Union[str, Sequence[str], None] = '653571ac65b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_storage_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('knowledge_bases', sa.Column('s3_original_key', sa.String(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('s3_extracted_key', sa.String(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('extracted_size_bytes', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('embedding_cost', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('s3_region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 's3_region')
    op.drop_column('knowledge_bases', 'embedding_cost')
    op.drop_column('knowledge_bases', 'chunk_count')
    op.drop_column('knowledge_bases', 'extracted_size_bytes')
    op.drop_column('knowledge_bases', 'file_size_bytes')
    op.drop_column('knowledge_bases', 'original_filename')
    op.drop_column('knowledge_bases', 's3_extracted_key')
    op.drop_column('knowledge_bases', 's3_original_key')
    op.drop_table('user_storage_usage')
    # ### end Alembic commands ###
