# Backward compatibility - imports from new modular structure
from models import (
    User,
    UsageLog,
    UserSettings,
    UserStorageUsage,
    Agent,
    AgentConfig,
    KnowledgeBase,
    KBIngestJob,
    WidgetDeployment,
    ChatSession,
    ChatMessage,
    KbChunk,
    KBSourceType,
    KBStatus,
    JobState,
    HumanAgent,
    AgentAssignment,
    Conversation,
    HumanPresence,
)

__all__ = [
    "User",
    "UsageLog",
    "UserSettings",
    "UserStorageUsage",
    "Agent",
    "AgentConfig",
    "KnowledgeBase",
    "KBIngestJob",
    "WidgetDeployment",
    "ChatSession",
    "ChatMessage",
    "KbChunk",
    "KBSourceType",
    "KBStatus",
    "JobState",
    "HumanAgent",
    "AgentAssignment",
    "Conversation",
    "HumanPresence",
]
